### PR TITLE
Add CMake support for cross-platform builds

### LINKED ISSUE #61: [Feature Request] Incorporate CMake for portable builds
I think it would be worth having the option to use CMake for building Morpho. This might make it easier for new users to get up and running without needing to worry (too much) about whether they're using the right linker flags for the various dependencies, regardless of the system they're running. This has the potential to also make Windows builds easier, though that will need some testing.

I have a minimal working example that can compile on my Linux system, but I'll need to do some more testing before I make a PR. The goal of this Issue is to have a place to discuss what needs to go into making this happen, as well as to discuss other relevant aspects of the build process.

### PR DESCRIPTION
**Pull request by mattsep**
This PR adds basic CMake support. With this, Morpho can, in principle, be compiled and installed using these basic steps (from the root directory of the project) on any platform:
```
cmake -B build && cd build
cmake --build .
cmake --install .
```
I say in principle because I haven't actually had a chance to test this on Windows or Mac yet. I think it should work on Mac as is, but for Windows we might need to do some trickery with regards to dependencies since there's no default search path for installed libraries.

Resolves #61

### CODE REVIEW

**Comment by ConduitDan** [comment]
If this is going to be the new way to build we should have the GIThub actions do them as well. We can take that up separately though

**Comment by softmattertheory** [comment]
I'm really excited about this! I'll check it out...

**Comment by softmattertheory** [comment]
@mattsep I'd love to resurrect this! We've moved on a bit from the version this was at [and this didn't seem to work on macOS] so I'll reach out and have a go at updating...

**Comment by softmattertheory** [comment]
With many thanks @mattsep for this fantastic suggestion, I am closing this PR. We have now transitioned to CMake for the 0.6 prerelease, which is available in https://github.com/Morpho-lang/morpho-libmorpho and https://github.com/Morpho-lang/morpho-cli. As 0.6.0 is completed, we'll transition libmorpho over to this repository. We're really grateful for this very helpful prototype, which helped us get this going.

**Pull request closed without merging**
