### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by softmattertheory**
This update fixes a number of outstanding issues: 

1) Modest improvements to the garbage collector which now gets better information from mutable objects. 
2) Updates to the examples including a fix to the tactoid example. 
3) Improvements to the manual, which now includes windows install instructions.

### CODE REVIEW

**Review by ConduitDan — APPROVED** [review]
Looks great, Do you want any tests locking down the size changes? Or will that be caught with valgrin?

**Comment by joshichaitanya3** [comment]
While we are on misc issues, there are two minor ones that I noticed:

1. In README.md, the formatting of the Linux / Mac commands (indented text) is different than the formatting for the commands for the WSL commands (code blocks). It'd be nice to make it consistent (I am fine with either, but have a slight preference for the code block as you get a copy-to-clipboard button next to those).
2. In the acknowledgements section of the manual, Matthew Peterson's first name needs one more 't' :)

**Comment by ConduitDan** [comment]
Created issue for the following

> While we are on misc issues, there are two minor ones that I noticed:
> 
>     1. In README.md, the formatting of the Linux / Mac commands (indented text) is different than that of the WSL commands (code blocks). It'd be nice to make it consistent (I am fine with either, but have a slight preference for the code block as you get a copy-to-clipboard button next to those).
> 
>     2. In the acknowledgements section of the manual, Matthew Peterson's first name needs one more 't' :)

Can you make issues for these so they are tracked and

**Comment by softmattertheory** [comment]
@ConduitDan a big problem is that it's quite hard to test the garbage collector automatically... we can activate STRESSTEST_GARBAGECOLLECTOR in build.h, which often shows up problems, but this is a fundamental challenge in GCs...

**Pull request merged**
