### PR TITLE
VTK fixes and improvements

### PR DESCRIPTION
**Pull request by joshichaitanya3**
Fixed a bug where the grade 3 elements were not being imported. 

Added a helper method `addvolume` to the MeshBuilder class to add volume elements. This is not needed, but I added it for consistency, since we already have the functions `addvertex` and `addfaces`.

Improved two tests based on previous suggestions, and added new tests to check that the maxgrade is correct.

Also added a test which imports a VTK file obtained externally. I should add that while the VTK format in general allows for a whole zoo of different elements, the current importer will silently fail (probably) if the file contains elements other than vertices, edges, faces or tetrahedrons. So, as it stands, the importer wouldn't work for all VTK files out there, but it should work for the ones generated through Morpho (luckily, the test case contains only vertices and faces). I will work on either making the importer more general, or having it break if the file cannot be read.

### CODE REVIEW

**Comment by ConduitDan** [comment]
> the current importer will silently fail (probably) if the file contains elements other than vertices, edges, faces or tetrahedrons
You should check what it does an perhaps not silently fail.

Do you have plans for a test that uses VTK to check the validity of the .vtk files exported from morpho?

**Comment by joshichaitanya3** [comment]
> You should check what it does an perhaps not silently fail.

I tried with the UnstructuredGrid example on the [VTK File format website](https://kitware.github.io/vtk-examples/site/VTKFileFormats/), and it threw a `Error 'ExpctArgNm' : Function 'Float' expects 1 numerical argument.`, probably because it tried to convert something that's not a number to a float. That example contains elements with up to 8 vertices...

> Do you have plans for a test that uses VTK to check the validity of the .vtk files exported from morpho?

Yes, that is in the works. Right now, the importer works under the assumption that the file is correctly formatted, but I am working on adding checks everywhere to ensure correct formatting.

**Comment by joshichaitanya3** [comment]
Also, here are a few reasons why I started with the Legacy format:
1. I tried using the [API](https://kitware.github.io/vtk-examples/site/Cxx/) that Kitware provides for generating VTK files, but it is written in C++, and it wasn't obvious to me how to incorporate it into the Morpho C code. (This would have been way nicer, since we'd only have to pass the information correctly to the API, and not worry about the file formatting.)
2. The normal format for the VTK files is XML based, and I figured I'll wait for a more general purpose xml module in Morpho before making a specific VTK one.
3. The Legacy format is the easiest to write explicitly without their API or xml support.

**Comment by softmattertheory** [comment]
> 1. I tried using the [API](https://kitware.github.io/vtk-examples/site/Cxx/) that Kitware provides for generating VTK files, but it is written in C++, and it wasn't obvious to me how to incorporate it into the Morpho C code. (This would have been way nicer, since we'd only have to pass the information correctly to the API, and not worry about the file formatting.)

One thing that will become available soon is the ability to link in C-written modules at runtime. This would enable, for example, compiling a C++ module and linking.

**Comment by joshichaitanya3** [comment]
> > 1. I tried using the [API](https://kitware.github.io/vtk-examples/site/Cxx/) that Kitware provides for generating VTK files, but it is written in C++, and it wasn't obvious to me how to incorporate it into the Morpho C code. (This would have been way nicer, since we'd only have to pass the information correctly to the API, and not worry about the file formatting.)
> 
> One thing that will become available soon is the ability to link in C-written modules at runtime. This would enable, for example, compiling a C++ module and linking.

Ooo that sounds exciting! It would definitely be the way to go for this in the future.

**Comment by joshichaitanya3** [comment]
Is this good to go? Let me know if there are other things I should edit.

**Comment by softmattertheory** [comment]
I think it's ready! @ConduitDan please merge!

**Review by ConduitDan — APPROVED** [review]

**Pull request merged**
