### PR TITLE
Added Tests for examples and debug builds

### PR DESCRIPTION
**Pull request by ConduitDan**
I've added a script to build the examples and a few debug flags that can turn off NaN boxing and stress test the garbage collector

I've also added to the git action on pull request to run these as well as building morphoview

I'm not adding any review requests yet as this is how I'm testing the github action.

### CODE REVIEW

**Comment by softmattertheory** [comment]
@ConduitDan  what's the status of this? Is the testing working or is it that we just need to resolve conflicts and merge or what?

**Comment by ConduitDan** [comment]
> @ConduitDan what's the status of this? Is the testing working or is it that we just need to resolve conflicts and merge or what?

I think what needs to happen is the following
1. Make a release branch that we pull from main and run these longer tests once a month
2. Break these out into smaller actions
3. Link these to icons on the home page

I also need to rebase this branch and to check what tests are still failing (we've fixed quite a few of these).
From my notes (https://wikis.uit.tufts.edu/confluence/x/MIe3C) It looks like the tests failing without NaN boxing are:

- if/truth ("" is false w/o nanbox and expected to be true)
- logical or_truth (print "s" or "ok" // expect: s | output "ok")

I can debug these and fix

**Comment by ConduitDan** [comment]
With some further thought it might be best to leave the "release" branch as main and create a development branch for adding new features that we can merge onto main at the end of the month

**Comment by ConduitDan** [comment]
Closing this for now so all the tests don't get re-run while i mess with the readme to add badges

**Pull request closed without merging**
